title: Sammy Metref # your name (or website title) here
logo: "/images/PhotoProfil.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Scientific Researcher at MEOM/IGE at Universit√© Grenoble Alpes 
  <br><br>
  <span style="color:red"> Data assimilation and inverse methods for spatial oceanography </span>
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/sammy-metref-8a920b27/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
